### ISSUE TITLE
Videoing into class, live script still at the same link?

### ISSUE THREAD

**Issue by WetlandWiggy** [gge-ucd/Discussion#11]
@ryanpeek I'm still on the east coast, so Katie is going to vid chat me into class today.  Is the link to the live(ish) script still https://dl.dropboxusercontent.com/u/108583959/wRangling_notebook.Rmd?  Thanks!

**Comment by ryanpeek** [comment]
Yes...that's the plan! In addition, remember to check the repository https://github.com/gge-ucd/wRangling_Seminar for the full code. You can always just clone a copy of this repository and simply update it every week using `Pull`. Then you'll have copies of everything we use. 

R
