### ISSUE TITLE
Wrapping text in R Script

### ISSUE THREAD

**Issue by hjkilleen** [gge-ucd/Discussion#12]
When I type comments into an R script, they run horizontally out of the script frame.  I really don't like scrolling to the right, and can't figure out how to solve the problem on Google.  Any ideas?

**Comment by vklo** [comment]
I figured out how to do this. Tools -> Global options -> Code -> Under general options, check the box "soft-wrap R source files"

**Comment by hjkilleen** [comment]
THANK YOU @vklo

**Comment by iheartrats** [comment]
Yay!

**Comment by ryanpeek** [comment]
Good work everyone!
