### ISSUE TITLE
Importing data?

### ISSUE THREAD

**Issue by MarthaZillig** [gge-ucd/Discussion#13]
I am trying to import my own data in the form of a .csv file.  I moved the file to my data folder, then when I try to open it from rstudio in a rmd, it comes up with the error: 
westernbirds <- read.csv(".../Data/Western_Data_CleanDates.csv")
cannot open file '.../Data/Western_Data_CleanDates.csv': No such file or directoryError in file(file, "rt") : cannot open the connection
> 

What is the correct way to load a csv file onto rstudio? Thanks!

**Comment by ryanpeek** [comment]
I think we solved this...it was a typo right?
