### ISSUE TITLE
not pushing it real good*

### ISSUE THREAD

**Issue by annholmes** [gge-ucd/Discussion#15]
I had been successfully pushing from RStudio to github earlier in the quarter. But I realized that my github repository is no longer being updated, even though I get a message that says "Everything up-to-date" when I push from RStudio. I'll troubleshoot this by trying to reconnect RStudio with github, and am wondering if anyone knows where things went wrong?

*Salt-N-Pepa reference

**Comment by Myfanwy** [comment]
Hi Ann,

I'd try reconnecting RStudio with github, and hopefully that works, but if not, can you push your commits from the command line successfully?

**Comment by ryanpeek** [comment]
So one thing that could've happened is you may have  different RStudio project (but similar/same name). Basically, you can have a local git repository in RStudio that doesn't actually have a home on Github...this could have happened when you were setting things up (pretty easy to click the wrong startup option). 

Can you open your RStudio project and try the following?

- under **Tools > Project Options**: 
     -  Click on the **`Git/SVN`** tab on the left...do you see a **_`git@github.com:`_** path to your project?

If so, great...that's a good sign. If not, you may have a local repository (which is fine, we can fix in class).

 - Under **Tools > Shell**: 
     - Should open a command line window on your computer. Type in  **`git status`**
     - Do you see something like: 
     > `On branch master`
     > `Your branch is up-to-date with 'origin/master'.`

Good luck!

**Comment by annholmes** [comment]
The problem seemed to be having too many (or the wrong?) Rproject files in the folder I wanted to sync with my repository.
