### ISSUE TITLE
error message when trying to push data

### ISSUE THREAD

**Issue by ceroddy6** [gge-ucd/Discussion#22]
Hi all,

After the recent download of all of that NEON data, I get error messages about large files when I try to push to my repository. Is anyone else having this issue?

**Comment by ryanpeek** [comment]
yes...forgot to mention you can't push files over 100MB to your repository using the protocol we've been using. Remind me and I can show you in class next week how best to deal with this. Essentially you'll need to install **Large File Size git** or **git-lfs** (https://git-lfs.github.com/). 

It works the same way our regular add > commit > push commands work, but it's just a different framework for large files. I'm not sure if we can use it within RStudio, so we may need to use a different git client/software (which comes with when you installed git).

Sorry for the confusion.
