### ISSUE TITLE
troubleshooting rgdal

### ISSUE THREAD

**Issue by lisamr** [gge-ucd/Discussion#23]
I was having issues properly installing rgdal during class this week. For some reason, "Path to PROJ.4 shared files: (**autodetected**)" which caused issues. Outlined in this document ed21692cda96a858e300a445a299e49e6db4cce4 solved the issues. Thanks @ryanpeek for the suggestions!

**Comment by lisamr** [comment]
Not sure why the commit link isn't showing up, but here's the html https://github.com/gge-ucd/lisa_rosenthal/commit/ed21692cda96a858e300a445a299e49e6db4cce4#diff-748907f9f9d738f577d7406d1f668ddf

**Comment by ryanpeek** [comment]
Also to clarify, this is related to needing to update your `gdal` installation, and these instructions will work on Mac/OSX or Linux computers. PC users may be less likely to encounter this problem and would need a different work-around. 

If OSX/Linux and need to install `gdal` or `geos` packages (not necessarily R related):

- Install Homebrew, an excellent package manager for Linux/Mac OSX. I use it all the time and it's sometimes the quickest way to get things installed. Website has the instructions you'll need to run in your Terminal (I believe you're on a Mac): https://brew.sh/
- Then try "`brew install gdal`" and "`brew install geos`", both are important spatial packages which may help the `rgdal` package in R behave better. 
- Re-install your `ggplot2`, `raster`, and `ggmap` packages in RStudio. Also make sure you have most current version of RStudio.

🔥 👍 🗄
