### ISSUE TITLE
error message cloning the repository into RStudio...

### ISSUE THREAD

**Issue by ryanpeek** [gge-ucd/Discussion#27]
When trying to set up and clone a repository in RStudio, these error messages popped up, both via **HTTPS** and **SSH** methods:

![image](https://user-images.githubusercontent.com/5864880/34972400-2434315c-fa36-11e7-8003-cb153e34ca9f.png)

![image](https://user-images.githubusercontent.com/5864880/34972413-3801d838-fa36-11e7-8b64-9b820c7e2816.png)

This was on MacOSX

**Comment by ryanpeek** [comment]
The solution we ended up checking (after making sure git was installed, R/RStudio were up to date):

 - Use the Terminal to clone a repository manually (not via RStudio) using `git clone`. We used `https`
 - Next we created a new RStudio project in that repository folder (but not a version controlled git project, just a regular new RStudio project, located in the same folder as the cloned repository).
 - Finally we made a change in the readme in RStudio, saved, and committed/pushed the changes using the git tab in RStudio (or using the terminal window in RStudio). 
 - A warning mentioned setting the global email/username with git config, so in command line or a Terminal window, use `git config --global user.name 'username or Your Name'` (*doesn't have to be github username*), and `git config --global user.email 'yourgithub@email'` (*MUST be github email*)

**Comment by rpesapan** [comment]
I'm having the same issue, but after I use Terminal and type `git clone` I'm given the following options:
usage: git clone [<options>] [--] <repo> [<dir>]

```
    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
    --progress            force progress reporting
    -n, --no-checkout     don't create a checkout
    --bare                create a bare repository
    --mirror              create a mirror repository (implies bare)
    -l, --local           to clone from a local repository
    --no-hardlinks        don't use local hardlinks, always copy
    -s, --shared          setup as shared repository
    --recursive           initialize submodules in the clone
    --recurse-submodules  initialize submodules in the clone
    -j, --jobs <n>        number of submodules cloned in parallel
    --template <template-directory>
                          directory from which templates will be used
    --reference <repo>    reference repository
    --dissociate          use --reference only while cloning
    -o, --origin <name>   use <name> instead of 'origin' to track upstream
    -b, --branch <branch>
                          checkout <branch> instead of the remote's HEAD
    -u, --upload-pack <path>
                          path to git-upload-pack on the remote
    --depth <depth>       create a shallow clone of that depth
    --single-branch       clone only one branch, HEAD or --branch
    --shallow-submodules  any cloned submodules will be shallow
    --separate-git-dir <gitdir>
                          separate git dir from working tree
    -c, --config <key=value>
                          set config inside the new repository
    -4, --ipv4            use IPv4 addresses only
    -6, --ipv6            use IPv6 addresses only
```
I'm not sure from your solution what I do next to create the clone. Do I want shared, local, bare, reference, or mirror repository? I assumed "reference" so I typed `git clone --reference <https://github.com/gge-ucd/w01-fix-readme-rpesapan.git>` and the outcome is:
`-bash: syntax error near unexpected token `newline'`

**Comment by ryanpeek** [comment]
Hi @rpesapan! Sorry I wasn't more explicit and clear, my fault. what you'll need to do is copy the https link (look for the big green button on your repository on Github.com ([Step 2 of these instructions](https://gge-ucd.github.io/R-DAVIS/setting_up_git.html)). After you have copied the `https` version of link, you can paste that into your git clone command so it should look like this:
 - `git clone https://github.com/gge-ucd/w01-fix-readme-rpesapan.git` (*But see steps below FIRST!*)


  - **Step 1**: Open your terminal window, and use the `cd` command to navigate to wherever you intend on saving your github/RStudio projects. Maybe make a folder called `github` and then use `cd ~/Documents/github` to change the directory to that location. 
  - **Step 2**:  Once you are in the correct directory (you can use `pwd` to double check where you are and make sure it's that folder from step 1), you can type `git clone` and then paste the link you copied from the green button on Github.com. It should look like this: `git clone https://github.com/gge-ucd/w01-fix-readme-rpesapan.git`. Hit enter.
  - **Step 3**: At this point it should start copying/creating your repository (though it may throw a warning about setting your email/username). When it's done (a fresh line shows up for you to enter stuff on the terminal), go ahead and close out of your terminal, and step through the creating a new RStudio project (as detailed above). If you get to this point we can work through these pieces together.

Hope this helps! 👍
