### ISSUE TITLE
installing R packages on linux, (installing tidyverse)

### ISSUE THREAD

**Issue by ryanpeek** [gge-ucd/Discussion#29]
Hi folks,

I've seen this issue a few times for folks trying to install packages on a Linux machine (running the Mint OS). I'm including it here in case I run into it again, or in case someone else runs into it.

Assume the user has just installed the most recent versions of R and RStudio (successfully). But then they try to install packages and nothing works. Every `install.packages()` attempt ends in `non-zero exit` error and nothing succeeds.  The following steps (or some combination) seemed to help.

1. Has a g++ or gcc compiler been installed? Check with `g++ --version`, if it doesn't exist, install with `sudo apt install g++`

2. Make sure there are the appropriate tools installed for package installation/builds. Use `sudo apt-get update` to update everything first. Then...

3. Install the libcurl library, which you'll need if you want to install most of the `tidyverse` libraries, use: `sudo apt-get install libcurl4-openssl-dev`

4. Finally, try installing the base R tools: `sudo apt-get install r-base-dev`.

Probably a good idea to reboot after you done all these things, and then open up your RStudio/R and try to install **`tidyverse`** or **`dplyr`**. If the above steps were successful, you should be able to successfully run `library(tidyverse)` (and you'll get some warnings about masked functions, which is normal).

Hope this is helpful at some point.

🔥 🚀 👍

**Comment by jealcalat** [comment]
Worked also on Debian 9.

**Comment by tadtenacious** [comment]
Ubuntu 18.04, had to go through the above and install two more packages: `sudo apt install libssl-dev libxml2-dev`

**Comment by RomeoAlphaYankee** [comment]
Thanks a million! I was having a devil of a time getting tidyverse and tidyquant to install on Mint.

**Comment by JF11579** [comment]
Thank you very much.  That helped a lot but left me unable  to install psidR.  I am also am having no luck installing devtools::install() or install_github or install.packages().  I suspect all of these have the same root cause but am new to Mint and cannot figure it out. Any ideas would be very appreciated.
