### ISSUE TITLE
manually installing packages

### ISSUE THREAD

**Issue by alanaroseo** [gge-ucd/Discussion#30]
Some of the dependencies for tidyverse didn't install, and couldn't be installed individually using install.packages(), I got the following message when I tried:
Package which is only available in source form, and may need compilation of
  C/C++/Fortran: ‘utf8’
  These will not be installed

Can I manually install them, and if so, how?
*Thanks!* @ryanpeek @taylorreiter @mikoontz

**Comment by ryanpeek** [comment]
@alanaroseo , good question! Haven't had something like this in awhile. I have two guesses, but may need to know a bit more about your system first.  Are you on a Windows 7 or 10 platform? (I'm assuming yes...). So, first option is unlikely but easier to deal with first, so let's try A, and if that doesn't work, try B.

 - **Option A**: If you open RStudio, go to Tools > Global Options, and select "Packages". At the top under CRAN Mirror, it probably says "Global CDN - RStudio". Click on Change, and select any of the other USA options. These are the different places that all mirror the R packages we use. I don't think it should matter, but worth a try. We can always go back and change this. After you select something different, hit *Ok* and *Ok* again. Then try to reinstall `tidyverse`. If this works, awesome. Odds are it won't 😿 . So...

 - **Option B**: This option requires a little more work. Happy to help if you need it, just let us know. But, I think you can do it! Here's what you need to do.
    - Open the Terminal in RStudio, and type "`g++ -v`" and see what you get. If it prints out a bunch of stuff and provides something at the end that looks like `gcc version X.X.X`, that means you have it installed.  If not (which is my suspicion), there will be a very short message or error saying nothing found or not installed. `g++` and `gcc` are one in the same, just different names. They are compilers that take raw code and build it into something your computer can use (i.e., a package). Essentially they are special code interpreters. Many systems come with a compiler pre-installed, but some don't. No big deal, just means you'll need to go download something called [RTools](https://cran.r-project.org/bin/windows/Rtools/). Currently you should hopefully be using the most recent version of R (3.4.x), so you'll want the *`Rtools34.exe`*.
    - There are some good instructions on how to install Rtools [here](https://github.com/stan-dev/rstan/wiki/Installing-RStan-on-Windows#toolchain). Just follow the directions from **Toolchain** up to **Configuration** (so stop at Configuration).  
   - After this is completed, close R and restart your computer. Then reboot, start up RStudio and try to install `tidyverse` again. 

I *hope* this solves this issue, but if not, please keep us posted. I'm leaving this issue open until we know things work.

**Comment by alanaroseo** [comment]
That didn't work, but I figured it out! Since RStudio was sharing a library with R, and my version of R was >3 years old (although RStudio was up to date), not all the tidyverse packages were available. Updating R did the trick, for some reason it is now making me install packages into a personal library, but I can get them to load, so that's not really an issue.
Thanks a bunch! @ryanpeek @mikoontz

**Comment by ryanpeek** [comment]
Aha!  Libraries and versions of R can be tricky, so it's always best to try and update the to most recent version. Glad you sorted it out!
