### ISSUE TITLE
Best practices for sourcing a function that you wrote

### ISSUE THREAD

**Issue by gabrielpsinger** [gge-ucd/Discussion#31]
@ryanpeek @mikoontz I was wondering if you could provide some guidelines or point me to some good resources for sourcing functions that we write.  I work with acoustic telemetry data sets that generate a lot of false positives.  I have developed a function to filter that data, and I will have to run it prior to almost every analysis that I do.  What are some best practices for saving/storing the original function so that it is easily accessible from any . Rproj that I am working on, how can I source it with out copying and pasting the original code into my new .R script, etc.  Any insights that you can provide would be greatly appreciated.

Thanks

**Comment by ryanpeek** [comment]
Hi @gabrielpsinger,
Excellent question. There are probably several different ways to do this, but I'll tell you the method I've used for this sort of problem. Typically, if you have a function you use frequently, you should save it in it's own script. To make sorting things easier, I usually create a functions folder within my scripts folder (i.e., `scripts/functions`). Furthermore, I also like to add a `f_` to the beginning of all my function scripts names as an easy way to recognize whether it's a stand-alone function or a script that actually processes data (*`f_my_custom_function.R`*).

Once you have your custom function saved as a script, you can add the following to the beginning of any script you want to use your function in (assuming your script is in a `scripts` folder):
```
source("functions/f_my_custom_function.R")
```
What's nice is you can then add/revise and fix your custom function, and just re-`source` it to make it available, which saves time editing code/pasting/etc. If the functions live somewhere else, that's fine, you just need to provide the full pathname.

I start almost every script I write with a section called **`Load Libraries & Functions`** where I load any libraries the script uses, along with the functions that it might need. That way anyone who needs to use the script will know right away what pieces they'll need in order for the script to work.

Hope this helps! If it works, please go ahead and close this issue.

**Comment by gabrielpsinger** [comment]
Thanks Ryan!
