### ISSUE TITLE
Style Guide for writing clean script

### ISSUE THREAD

**Issue by gabrielpsinger** [gge-ucd/Discussion#32]
When @taylorreiter was lecturing, she briefly mentioned a style guide.  My script files are generally pretty messy and I would like to work on cleaning them up.  Is there a style guide that that R Davis group endorses?

**Comment by taylorreiter** [comment]
Yes! From the Data Carpentry Ecology R lessons:
"In R, three popular style guides are [Google’s](https://google.github.io/styleguide/Rguide.xml), [Jean Fan’s](http://jef.works/R-style-guide/) and the [tidyverse’s](http://style.tidyverse.org/)." 

You can read through these and take your pick. 

My personal favorite is [Hadley Wickham's](http://adv-r.had.co.nz/Style.html).

**Comment by gabrielpsinger** [comment]
Thanks
