### ISSUE TITLE
fatal error: could not read from remote repository

### ISSUE THREAD

**Issue by sagaffney** [gge-ucd/Discussion#35]
Hi @ryanpeek, I successfully committed and pushed changes last Friday but when I realized I forgot a line of code today, I was able to commit but not push. I get the error below: 

"ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists."

I didn't change anything in between when it worked and now. Any ideas?

**Comment by ryanpeek** [comment]
Hi @sagaffney, 
Make sure your VPN isn't connected (if you have one, like Open Pulse Secure). Beyond that, I'd need to trouble shoot in class to get a handle on what might be going awry.  What does `git status` tell you (in your Terminal window of your project or repository?)

**Comment by ryanpeek** [comment]
@sagaffney One other thought. Try pushing from command line (the Terminal window in RStudio while in your Rproject, use:`git push`). If successful, it may ask for your username and password. Enter that info. If it is successful, you can close that window and RStudio, reopen, and try to make some little change (i.e., add/revise something in your readme), and this time use commit and push from the RStudio **git** tab. Hopefully that will work.

**Comment by sagaffney** [comment]
yeah I was dumb and had Open Pulse Secure connected
