### ISSUE TITLE
How can I not use git sometimes? 

### ISSUE THREAD

**Issue by TryAgainTryAgain** [gge-ucd/Discussion#38]

**Comment by mikoontz** [comment]
Hmm, what do you mean?

**Comment by ryanpeek** [comment]
@TryAgainTryAgain Can you give us some more details? Thanks!

**Comment by mikoontz** [comment]
I got this from @TryAgainTryAgain in an email, that I incorrectly assumed would also be posted here: "Long story, I’ll explain in class. But I figured a work around :).   Tried to delete the discussion, but couldn’t. "
