### ISSUE TITLE
Can't find repositories

### ISSUE THREAD

**Issue by alanaroseo** [gge-ucd/Discussion#39]
Hi @ryanpeek and @mikoontz ,
Did I somehow put my learning tidyverse repo in the wrong place? I don't see my partner's or  learning-tidyverse-mikoontz, or any others on the gge-ucd front page where the week 1 repos were.  I think must have missed something...
😃
thanks!
Alana

**Comment by mikoontz** [comment]
Hi @alanaroseo!

Nope, you didn't miss a thing. We thought the repositories would automatically go to the Ents team and it doesn't look like they did. Stand by for instructions on how to add your own repository to the team (which you'll have to do each time we create a new repository going forward). Basically, you go to your repository, go to settings, go to collaborations, click the dropdown menu with "add to team", and select "Ents". Screenshots to come!

**Comment by mikoontz** [comment]
Check here for screenshots: https://github.com/orgs/gge-ucd/teams/ents/discussions/6
