### ISSUE TITLE
repo location

### ISSUE THREAD

**Issue by gabrielpsinger** [gge-ucd/Discussion#40]
@mikoontz  I have a couple of questions. 

1) Is my repo in the right [place](https://github.com/gge-ucd/learning-tidyverse-gabrielpsinger)  or should it be under 'ents'?

2) The link to your code didn't work for me and I don't see a repo for my coding partner.  Did I screw something up here?

Gabe

**Comment by mikoontz** [comment]
Good questions!

1. I'm writing up a note on this now for the Discussion board. It should be under 'ents' and we thought it would automatically go there. It doesn't seem to do that automatically, so stay tuned for the instructions on adding it to the team. Basically, you go to your repository, go to settings, go to Collaborations, click the dropdown menu with "Add a team", click Ents, and then it should show up!

2. Nope! Your partner is no longer enrolled, so go ahead and comment on my repository. (Which is now part of the Ents team). I'll update that code partner spreadsheet.

**Comment by mikoontz** [comment]
Check here for screenshots: https://github.com/orgs/gge-ucd/teams/ents/discussions/6
