### ISSUE TITLE
Using FARM with private github repo

### ISSUE THREAD

**Issue by JepsonNomad** [gge-ucd/Discussion#46]
Hey folks - do you know if there's a way to use code and data from a private github repo on the UC Davis FARM? Historically I've used a shell script (which was uploaded onto my FARM account) to call an R script (also on my FARM account) that works with data that was already uploaded onto the FARM.

**Comment by MCMaurer** [comment]
I'm not sure if this is possible, I haven't seen any documentation on it. I just use `rsync` to send files back and forth, so I have a little rsync script to send files to the FARM, and one to take them from the FARM. Then for every script I want to run, I actually have two scripts: my R script, which has all the code, plus makes sure to save the output files, and then a shell script that contains all the proper SLURM headers and then calls the R script and runs it. I have my local folder set up as a repo, so after I pull results from the FARM, I can push those results and stuff to GitHub. I don't know if there's a more direct way to interface between GitHub and the FARM though

**Comment by JepsonNomad** [comment]
Ok, that's the approach I've used up to this point as well. Thanks Michael.
