### ISSUE TITLE
GitHub script file > RAW > Save As... 

### ISSUE THREAD

**Issue by caparisek** [gge-ucd/Discussion#48]
Hi @MarthaWohlfeil, @MCMaurer, @ryanpeek,

@Rtallman01 had an issue with Part 2 of the assignment. We figured out a workaround and completed the assignment but would like to know why step 2-3went wrong. 

After clicking RAW and getting redirected to a plaintext version on a website background, neither of us can "save as" a .R file. I'm only getting the option "save page as" which gives me even less options, whereas Rachelle can only save as a .txt. What are we doing wrong? 

Our workaround was to copy and paste the code into a new script file and save the file by the exact same file name as the partner we checked.

Instructions for Part 2: #Part II: Code Review
#1) Find your code partner’s repository on GitHub, click on the scripts folder, and find the script named w3_assignment_ABC.R
#2) Click on the script, then find the RAW button on the right hand side of the screen. Click on RAW.
#3) You should see a plain text version of the script. Right click anywhere on the page, and select “Save As”, save the script to your scripts folder in your repository. Make sure to change the file extension to .R (instead of .txt).

(Attached is my screenshot) 
![screen shot 2019-02-04 at 10 38 29 pm](https://user-images.githubusercontent.com/46494669/52258710-f9c31400-28d4-11e9-9fec-a3f7e59d8a0d.png)

**Comment by MarthaZillig** [comment]
@caparisek @rtallman01 Hmm this is strange. You should be able to right click and "Save As" and save the file as a "text document" which you can then change the file extension to ".R" Potentially this is a Mac problem?

Your work around seems fine for now, but lets be sure to take a look at what is going on before or after class today.

**Comment by caparisek** [comment]
Thanks, will do! 
I have a mac, Rachelle has a PC - from what I overhear, it sounds like a few others had this issue too.

**Comment by ryanpeek** [comment]
Hi @caparisek and @rtallman01!

Not sure why `Save As` isn't an option, but the text document option is typical on Windows. One option you may see is to save as "`text`", but a small dropdown may also have the option to save "All Files"....select that and then add `.R` the end of your file name. Or as @MarthaWohlfeil said you can change the extension later. I'll poke around a bit more for the save as option...

**Comment by caparisek** [comment]
Thanks @ryanpeek, 
I couldn't figure out how to change my Mac's trackpad right-click, but I checked how it works in Chrome vs Safari like you suggested and it does work in Chrome just fine! Strange..

**Comment by rtallman01** [comment]
Hi everyone! So I have a PC and tried @MarthaWohlfeil and @ryanpeek  suggestion of click save as and hitting the drop down option. I've tried that and hitting the All Files option and saving it as .R but when I pulled the file up in R it still read it only as a txt file

Here is a screenshot of what it looks like from my computer.

![homework_4](https://user-images.githubusercontent.com/46497779/52353751-ff5b4f80-29e3-11e9-812e-9936953e10c3.png)

**Comment by rtallman01** [comment]
I figured it out! Looks like when I save it to All Files I need to go back in and change the name it originally saves it as .R.txt and I just needed to delete the .txt part and it seems to have worked. Sorry this might have been said earlier but I didn't really understand. I didn't realize the file would continue to be saved as a text file even after I selected All Files.

**Comment by ayman-ashine** [comment]
`<script src="https://raw.githubusercontent.com/.../.../main/.../app.js"></script>`
This action doesn't work,
Here are the error message.
![Screenshot 2022-12-08 201624](https://user-images.githubusercontent.com/93885462/206547180-8626cc03-0149-4516-bbb9-fa001dcc9320.png)
