### ISSUE TITLE
issues with git when updating to Mojave OSX

### ISSUE THREAD

**Issue by ryanpeek** [gge-ucd/Discussion#52]
@gge-ucd/hippogriffs, I know some folks were have this issue, so I'm tagging everyone (just in case). The following only applies to folks who are working on a Mac, and who recently updated to the Mojave OSX.

Several folks were encountering problems where the git tab disappeared from the RStudio browser. Or your project just no longer functions as a git repository locally. 

**A potential solution!** 👍 

After installing Mojave, you likely need to reinstall command line tools (and friends). Try running from a Terminal window:

```
xcode-select --install
```
Also when you run the following `/usr/bin/git --version`, you may get prompted to update your xcode as well...either way the main thing that needs to happen is to update and *accept the license agreement* so everything will function again. This may require a restart of your computer, but at minimum a restart of RStudio.

Please let me know (@ryanpeek) if this works for you!  Filing issues is a way to be an active participant, so don't be shy about commenting. We'll talk more about issues and github etiquette next week.

**Comment by caparisek** [comment]
Hi all - I had to attend via live-streaming this past week but I overheard this issue over the break. I'm on a Mac with the most recent update my computer is aware of; I haven't experienced an issue yet. The issue others are experiencing does sound similar to when I was trying to access my git version-control files on a new computer (that didn't "know git" yet) a few weeks back and the git tab wouldn't show. Hope re-running the lines work; it did for me. #participating
