### ISSUE TITLE
Issue with cloning repository

### ISSUE THREAD

**Issue by Oyewumi97** [gge-ucd/Discussion#56]
I have been trying to clone a repository in R. 
Followed the process shared but keep getting the error below.

fatal: could not create work tree dir 'Team-Watson-First-Task.': Invalid argument
Can anyone help please?

**Comment by MarthaZillig** [comment]
Hi! I think what is going on here is that you have a character in your name that github doesn't like. Did you include that period at the end of "Team-Watson-First-Task"? The period is likely what's causing your problem, remove the period and try again. Let me know if that works!
