### ISSUE TITLE
Error messages... R not recognizing characters I type?

### ISSUE THREAD

**Issue by tombatter** [gge-ucd/Discussion#7]
When I manually type commands, I get error codes such as:
Error: unexpected '<' in "df <- read.csv(<"
or
Error: unexpected '[' in "["
However, if I copy and paste from what we did in class, or copy and paste from code via an instructional website, the command works. Any idea what the deal is here & how to fix it?

**Comment by ryanpeek** [comment]
As typed, `df <- read.csv(<` would give you an error. Similarly, a single bracket would throw an error if you didn't have something before or after. R, and coding in general, requires meticulous attention to coding details (`" "` vs. `""` does matter in some places). While this is extremely annoying at first, get used to scrutinizing your code, finding some typos, running things, realizing there's something else you missed, and continuing ...

Pretty soon it will be second nature, but in the mean time, feel free to copy and paste and keep a sharp eye out!  I'm linking to some good resources on code etiquette and details below:

@gge-ucd/ewoks 

- http://adv-r.had.co.nz/Style.html
- https://nicercode.github.io/blog/2013-04-05-why-nice-code/
