### ISSUE TITLE
dplyr Exercise 7 instructions unclear

### ISSUE THREAD

**Issue by davhernandez** [gge-ucd/Discussion#8]
@ryanpeek 
I need some clarification for exercise 7 in the dplyr section

https://gge-ucd.github.io/wRangling-Ecology/assignments/r-data/

It refers to task 4 of exercise 6. However, there are only 3 numbered tasks. Which data table are you trying to reference?

**Comment by ryanpeek** [comment]
Yup, let's not worry about it. I'll go over dplyr in class with some additional examples...the data in question is from another lesson that we haven't done (and might not get to). It's a result of the course the website is based on, and re-arranging things. Apologies.
